### PR TITLE
[FIX] l10n_ar_ux: Print Duplicate/Triplicate Copie

### PR DESCRIPTION
**Pull request by zaoral**
ticket 65337

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/727).

**Comment by zaoral** [comment]
@roboadhoc r+
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: you can't review+.

**Comment by dbollini** [comment]
@roboadhoc r+
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @dbollini: you are not allowed to override this status.

**Pull request closed without merging**
