### PR TITLE
[FIX] l10n_ar_ux: invoice report sign and update manifest version

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/770).

**Comment by jjscarafia** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@jjscarafia you may want to rebuild or fix this PR as it has failed CI.

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#771

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#771

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#771

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#771

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#771

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#771

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#771

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#771

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#771

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#771

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#771

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#771

**Pull request closed without merging**
