### PR TITLE
[FW][FIX] l10n_ar_ux: fix in order to keep the original date if it exists

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina#811

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/817).

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @zaoral cherrypicking of pull request ingadhoc/odoo-argentina#811 failed.

stdout:
```
Auto-merging l10n_ar_ux/models/account_move.py
CONFLICT (content): Merge conflict in l10n_ar_ux/models/account_move.py

```

stderr:
```
20:39:22.022352 git.c:444               trace: built-in: git cherry-pick b77cabc9eea98d5f433727f39d1c179ec0767ae7
error: could not apply b77cabc9... [FIX] l10n_ar_ux: fix in order to keep the original date if it exists
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @zaoral this PR was closed then reopened. It should be merged the normal way (via @roboadhoc)

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
