### PR TITLE
[IMP] l10n_ar_ux: re-add check

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/570).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
Because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by jjscarafia** [comment]
@roboadhoc rebase-ff p=0

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward

**Pull request closed without merging**
