### PR TITLE
[FIX] l10n_ar_ux: Fixed report payment_group w/ multicurrency

### PR DESCRIPTION
**Pull request by feg-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/1009).

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@feg-adhoc @rov-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#1010

**Comment by fw-bot-adhoc** [comment]
@feg-adhoc @rov-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#1010

**Pull request closed without merging**
