### PR TITLE
[FW][ADD] l10n_ar_ux: Debit note withou debit origin

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Necessary when creating a debit note different from view, for example, from python or API, an automated action, or an ir.cron.

Forward-Port-Of: ingadhoc/odoo-argentina#671

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/697).

**Comment by fw-bot-adhoc** [comment]
@zaoral @ica-adhoc this PR targets 16.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@zaoral @ica-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
