### PR TITLE
[IMP] l10n_ar_purchase: show only vat tax

### PR DESCRIPTION
**Pull request by jjscarafia**
Al igual que en facturas y ventas, solo mostramos columna de IVA en reporte argentino

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/993).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#1006

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#1006

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#1006

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#1006

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#1006

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#1006

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#1006

**Pull request closed without merging**
