### PR TITLE
[IMP] l10n_ar_account_withholding: wh report

### PR DESCRIPTION
**Pull request by ica-adhoc**
Change "Customer" to "Proveedor in withholding certificate

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/685).

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#686

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#686

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#689

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#689

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#689

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#689

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#689

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#689

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#689

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#689

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#689

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#689

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#689

**Pull request closed without merging**
