### PR TITLE
Revert "[FIX]l10n_ar_ux: margin for header in report_delivery_doc"

### PR DESCRIPTION
**Pull request by zaoral**
This reverts commit 4c45ea7898ead7adf45eeede524bdf63e359f134.

Ticket 80610

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/923).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: you can't review+.

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
