### PR TITLE
[IMP] *: better payments views

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/884).

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jjscarafia @rov-adhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
