### PR TITLE
[FIX] l10n_ar_ux: payment group report check data

### PR DESCRIPTION
**Pull request by ica-adhoc**
Now the data of checks prints correctly in the payment group report

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/650).

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#651

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#651

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#651

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#651

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#651

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#651

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#651

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#651

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#651

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#651

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#651

**Pull request closed without merging**
