### PR TITLE
[MIG][16.0] l10n_ar_purchase and l10n_ar_purchase_stock

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/701).

**Comment by vib-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@augusto-weiss @vib-adhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by bruno-zanotti** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Pull request closed without merging**
