### PR TITLE
[FIX] l10n_ar_ux: payment group report check data

### PR DESCRIPTION
**Pull request by ica-adhoc**
TICKET 57508 - fix qweb report variables

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/656).

**Review by zaoral — APPROVED** [review]

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#662

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#662

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#662

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#662

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#662

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#662

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#662

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#662

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#662

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#662

**Pull request closed without merging**
