### PR TITLE
[IMP] new payment report and other fixes

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/821).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Pull request closed without merging**
