### PR TITLE
[FW][IMP] l10n_ar_account_withholding: optimizar mensaje error padron ARBA.

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Tarea: 37771

Forward-Port-Of: ingadhoc/odoo-argentina#825

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/832).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral ci/runbot-oba failed on this forward-port PR

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@pablohmontenegro you may want to rebuild or fix this PR as it has failed CI.

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
