### PR TITLE
15.0 rebase from 13.0

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/555).

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests, ci/argentina-ce, ci/argentina-ee

**Comment by nicomacr** [comment]
@roboadhoc override=ci/argentina-ce

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. You are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/argentina-ee

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc override=ingadhoc/account-payment#257

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. You are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc p=1

**Comment by nicomacr** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward

**Pull request closed without merging**
