### PR TITLE
[FW][FIX] l10n_latam_country_code does not exist anymore

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina#644

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/646).

**Comment by fw-bot-adhoc** [comment]
@odoo-mastercore @nicomacr cherrypicking of pull request ingadhoc/odoo-argentina#644 failed.

stdout:
```
Auto-merging l10n_ar_ux/views/account_move_view.xml
CONFLICT (content): Merge conflict in l10n_ar_ux/views/account_move_view.xml

```

stderr:
```
15:20:47.817939 git.c:439               trace: built-in: git cherry-pick fe7441405daf8e503e113e2d834b595f12596a47
error: could not apply fe744140... [FIX] l10n_latam_country_code does not exist anymore
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
