### PR TITLE
[FIX] l10n_ar_withholding_ux : Add monkey patch to clean _synchronize…

### PR DESCRIPTION
**Pull request by maq-adhoc**
…_to_moves

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/828).

**Comment by jjscarafia** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
@maq-adhoc @jjscarafia linked pull request(s) ingadhoc/account-payment#472 not ready. Linked PRs are not staged until all of them are ready.

**Pull request closed without merging**
