### PR TITLE
[FW][FIX]l10n_ar_ux: margin for header in report_delivery_doc

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina#914

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/918).

**Comment by fw-bot-adhoc** [comment]
This PR targets 17.0 and is part of the forward-port chain. Further PRs will be created up to 18.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by ced-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @ced-adhoc. I'm afraid I can't do that.

**Comment by zaoral** [comment]
We discard this pr because it get us trouble with the invoice report.
We will implement something different in 16.0 and make the FW with the fix 17.0 later this week

**Pull request closed without merging**
