### PR TITLE
[FW][FIX] l10n_ar_ux: check country code in doc domain

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina#558

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/559).

**Comment by fw-bot-adhoc** [comment]
Ping @Bruno-Zanotti
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jjscarafia** [comment]
@fw-bot-adhoc r+

**Comment by nicomacr** [comment]
@roboadhoc p=0

**Pull request closed without merging**
