### PR TITLE
[FW] WIP

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina#935

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/955).

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @rov-adhoc this PR targets 18.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by rov-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by roboadhoc** [comment]
@jjscarafia @rov-adhoc linked pull request(s) ingadhoc/account-payment#564 not ready. Linked PRs are not staged until all of them are ready.

**Comment by rov-adhoc** [comment]
@fw-bot-adhoc r+

**Pull request closed without merging**
