### PR TITLE
[FIX] l10n_ar_ux: only apply to AR

### PR DESCRIPTION
**Pull request by zaoral**
Avoid multi loc companties, only change the way that the manual numbering field works if the company is AR

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/677).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: you can't review+.

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
