### PR TITLE
[FW][IMP] l10n_ar_purchase: show only vat tax

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Al igual que en facturas y ventas, solo mostramos columna de IVA en reporte argentino

Forward-Port-Of: ingadhoc/odoo-argentina#993

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/1005).

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @zaoral cherrypicking of pull request ingadhoc/odoo-argentina#993 failed.

stdout:
```
Auto-merging l10n_ar_purchase/i18n/es.po
Auto-merging l10n_ar_purchase/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_purchase/__manifest__.py

```

stderr:
```
12:49:39.647516 git.c:444               trace: built-in: git cherry-pick 8441edc435f61cb66d56df86b94c563e3da19ef3
error: could not apply 8441edc4... [IMP] l10n_ar_purchase: show only vat tax
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jjscarafia** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Pull request closed without merging**
