### PR TITLE
[FIX] l10n_ar_withholding_ux: Agregamos el numero de cheque al reporte

### PR DESCRIPTION
**Pull request by mem-adhoc**
Ticket: 82672

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/949).

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#966

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#966

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#966

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#966

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#966

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#966

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#966

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#966

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#966

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#966

**Pull request closed without merging**
