### PR TITLE
[IMP] l10n_ar_ux: better fiscal positions auto-detect

### PR DESCRIPTION
**Pull request by jjscarafia**
Revert when https://github.com/odoo/odoo/pull/81912 is merged

closes ingadhoc/odoo-argentina#571

Signed-off-by: Juan José Scarafía <jjs@adhoc.com.ar>

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/572).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina#573

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina#573

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina#573

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina#573

**Pull request closed without merging**
