### PR TITLE
[FIX] l10n_latam_country_code does not exist anymore

### PR DESCRIPTION
**Pull request by odoo-mastercore**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/644).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@odoo-mastercore Thanks for the fixing.

**Comment by fw-bot-adhoc** [comment]
@odoo-mastercore @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina#646

**Pull request closed without merging**
