### PR TITLE
[IMP]l10n_ar_ux:better design on payment qr on invoices

### PR DESCRIPTION
**Pull request by PabloPaezSheridan**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/560).

**Review by bruno-zanotti — APPROVED** [review]
+1

**Comment by PabloPaezSheridan** [comment]
r+

**Comment by PabloPaezSheridan** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @PabloPaezSheridan. You can't review+.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina#561

**Pull request closed without merging**
