### PR TITLE
[FIX] l10n_ar_ux: change invoice_payment_state

### PR DESCRIPTION
**Pull request by ica-adhoc**
ticket 70257

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/785).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#786

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#786

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#786

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#786

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#786

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#786

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#786

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#786

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#786

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#786

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#786

**Pull request closed without merging**
