### PR TITLE
[FW][IMP]l10n_ar_ux: Hide change rate button for non-argentinan companies

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket:53397

Forward-Port-Of: ingadhoc/odoo-argentina#639

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/642).

**Comment by fw-bot-adhoc** [comment]
Ping @mem-adhoc, @zaoral cherrypicking of pull request ingadhoc/odoo-argentina#639 failed.

stdout:
```
Auto-merging l10n_ar_ux/views/account_move_view.xml
CONFLICT (content): Merge conflict in l10n_ar_ux/views/account_move_view.xml
Auto-merging l10n_ar_ux/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_ux/__manifest__.py

```

stderr:
```
13:22:00.161295 git.c:439               trace: built-in: git cherry-pick 7c01b72d56851e88f564c710d4016125a9fdc429
error: could not apply 7c01b72d... [IMP]l10n_ar_ux: Hide change rate button for non-argentinan companies
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by mem-adhoc** [comment]
@nicomacr Hola Nico buenos días, necesitamos mezclar este cambio pero seguimos con el problema en rojo de runbot nos puedes ayudar ?

**Comment by nicomacr** [comment]
@roboadhoc p=0

**Pull request closed without merging**
