### PR TITLE
17.0 t 34377 jjs 29.02

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/812).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
@roboadhoc r-

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Pull request closed without merging**
