### PR TITLE
[FW][IMP]l10n_ar_ux:better design on payment qr on invoices

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina#560

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/561).

**Comment by fw-bot-adhoc** [comment]
Ping @PabloPaezSheridan, @nicomacr cherrypicking of pull request ingadhoc/odoo-argentina#560 failed.

stdout:
```
Auto-merging l10n_ar_ux/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_ux/__manifest__.py

```

stderr:
```
12:10:35.826824 git.c:439               trace: built-in: git cherry-pick b40033cd7f13a97aa55793c91a28524e46e6fc54
error: could not apply b40033cd... [IMP]l10n_ar_ux:better design on payment qr on invoices
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Pull request closed without merging**
