### PR TITLE
[FW][FIX] l10n_ar_ux: change invoice_payment_state

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
ticket 70257

Forward-Port-Of: ingadhoc/odoo-argentina#785

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/786).

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc cherrypicking of pull request ingadhoc/odoo-argentina#785 failed.

stdout:
```
Auto-merging l10n_ar_ux/views/report_invoice.xml
Auto-merging l10n_ar_ux/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_ux/__manifest__.py

```

stderr:
```
13:15:21.746058 git.c:444               trace: built-in: git cherry-pick 0fdfba95f909183c168ef416e1402f479933edf6
error: could not apply 0fdfba95... [FIX] l10n_ar_ux: change invoice_payment_state
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jjscarafia** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Pull request merged**
