### PR TITLE
[FW][FIX] l10n_ar_account_withholding: arba error 11

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Bad If was returning an error when we have a partner that is no inscripto.

Forward-Port-Of: ingadhoc/odoo-argentina#674

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/676).

**Comment by fw-bot-adhoc** [comment]
@zaoral @ica-adhoc this PR targets 16.0 and is the last of the forward-port chain containing:
* ingadhoc/odoo-argentina#675

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
@fw-bot-adhoc r+

**Pull request closed without merging**
