### PR TITLE
[FIX] l10n_ar_ux: monkey patch post_load

### PR DESCRIPTION
**Pull request by zaoral**
this way the monkey patch only is loaded if the module is installed.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/722).

**Comment by jjscarafia** [comment]
@roboadhoc r+ override=ci/runbot-modified-modules

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia: you are not allowed to override this status.

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/runbot-modified-modules

**Pull request closed without merging**
