### PR TITLE
[FIX] l10n_ar_loyalty: mark module as auto install

### PR DESCRIPTION
**Pull request by zaoral**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/716).

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@mem-adhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by zaoral** [comment]
@roboadhoc override=ci/runbot-oba

**Pull request closed without merging**
