### PR TITLE
[FIX] l10n_ar_account_withholding: render report

### PR DESCRIPTION
**Pull request by ica-adhoc**
Now report render on mail_compose_message not fails when try send the payment's mail

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/709).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@zaoral you may want to rebuild or fix this PR as it has failed CI.

**Comment by zaoral** [comment]
@roboadhoc override=ci/runbot-oba

**Pull request closed without merging**
