### PR TITLE
[FIX] l10n_ar_loyalty: se elimina modulo por desuso

### PR DESCRIPTION
**Pull request by mem-adhoc**
Task: 32083

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/726).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@zaoral you may want to rebuild or fix this PR as it has failed CI.

**Comment by zaoral** [comment]
@roboadhoc override=ci/runbot-oba

the runbot is feailing related to another pr https://runbot.adhoc.com.ar/runbot/build/29967

**Pull request closed without merging**
