### PR TITLE
[ADD] l10n_ar_bank: agregar banco Bica

### PR DESCRIPTION
**Pull request by pablohmontenegro**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/872).

**Comment by zaoral** [comment]
@roboadhoc r+
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@zaoral you may want to rebuild or fix this PR as it has failed CI.

**Comment by zaoral** [comment]
NOTE: we force the merge because we have and external red not related to this PR

**Pull request closed without merging**
