### PR TITLE
[FIX] l10n_ar_account_withholding: trying to avoid

### PR DESCRIPTION
**Pull request by zaoral**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/795).

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by pablohmontenegro** [comment]
@roboadhoc r-

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
