### PR TITLE
[IMP] adapt pay rerport to new _payment_group_currency

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/991).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jjscarafia because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by jjscarafia** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Pull request closed without merging**
