### PR TITLE
[FIX] l10n_ar_ux: adjust method name

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/679).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@zaoral you may want to rebuild or fix this PR as it has failed CI.

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
