### PR TITLE
[IMP] l10n_ar_ux: add currency amounts on invoice report

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/764).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#766

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#766

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#766

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#766

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#766

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#766

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#766

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#766

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#766

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#766

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#766

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#766

**Pull request closed without merging**
