### PR TITLE
[FW][FIX] l10n_ar_ux: Fix when calculating computed_currency_rate and have l10n_ar_currency_rate set in 1.0

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina#971

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/976).

**Comment by fw-bot-adhoc** [comment]
This PR targets 17.0 and is part of the forward-port chain. Further PRs will be created up to 18.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by rov-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @feg-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @rov-adhoc: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
