### PR TITLE
[FIX] l10n_ar_withholding_ux: Fix in payment receipt pdf creator view when having a signature set for a company

### PR DESCRIPTION
**Pull request by rov-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/906).

**Comment by maq-adhoc** [comment]
@rov-adhoc r+

**Comment by maq-adhoc** [comment]
@rov-adhoc r+

**Comment by cav-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
