### PR TITLE
[FW][FIX] l10n_ar_ux: Get Docs traceback when no res

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket 83482

Forward-Port-Of: ingadhoc/odoo-argentina#953

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/954).

**Comment by fw-bot-adhoc** [comment]
This PR targets 17.0 and is part of the forward-port chain. Further PRs will be created up to 18.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro ci/runbot-oba failed on this forward-port PR

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@pablohmontenegro you may want to rebuild or fix this PR as it has failed CI.

**Comment by pablohmontenegro** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: you are not allowed to override this status.

**Comment by pablohmontenegro** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: you are not allowed to override this status.

**Pull request closed without merging**
