### PR TITLE
M-[FW][IMP] l10n_ar_ux: search currenct by afip code

### PR DESCRIPTION
**Pull request by zaoral**
x-original commit: 16a3044a0a8f81c21f794e8636e1e64bb7c6e4c8

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/691).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: you can't review+.

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
