### PR TITLE
[15.0][MIG] l10n_ar_ux

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/567).

**Comment by jjscarafia** [comment]
@roboadhoc r+ override=ci/oba_without_tests

mezclamos igual, el warning es por un PR abierto que tenemos en odoo

**Comment by roboadhoc** [comment]
@jjscarafia, you may want to rebuild or fix this PR as it has failed CI.

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/argentina-ee

**Comment by jjscarafia** [comment]
@roboadhoc rebase-ff

**Comment by jjscarafia** [comment]
@roboadhoc p=1

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward

**Pull request closed without merging**
