### PR TITLE
[FIX] l10n_ar_account_withholding: Add title attribute to icon button

### PR DESCRIPTION
**Pull request by dal-adhoc**
- Adds a title attribute to a button that has an icon without text.
- Remove trailing space at end of icon attribute.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/990).

**Review by zaoral — APPROVED** [review]

**Comment by zaoral** [comment]
@fw-bot-adhoc fw=no

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
Gracias Dani!! @dal-adhoc

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#998

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#998

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#998

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#998

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#998

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#998

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#998

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#998

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#998

**Comment by fw-bot-adhoc** [comment]
@dal-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#998

**Pull request closed without merging**
