### PR TITLE
[FIX] l10n_ar_ux: sanitize document_number

### PR DESCRIPTION
**Pull request by cav-adhoc**
Removes added characters (e.g. (1)) for repeated document numbers before sending them to l10n_ar method that returns document number parts

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/862).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jjscarafia you may want to rebuild or fix this PR as it has failed CI.

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
