### PR TITLE
[MIG] l10n_ar_purchase_stock: Migration to 17.0

### PR DESCRIPTION
**Pull request by pablohmontenegro**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/820).

**Review by zaoral — APPROVED** [review]

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
@roboadhoc retry

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: retry makes no sense when the PR is not in error.

**Pull request closed without merging**
