### PR TITLE
[ADD] l10n_ar_ux: Controllador Fiscal new POS

### PR DESCRIPTION
**Pull request by zaoral**
ticket 42561

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/909).

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#936

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#936

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#936

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#936

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#936

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#936

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#936

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#936

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#936

**Pull request closed without merging**
