### PR TITLE
[FIX]l10n_ar_ux: margin for header in report_delivery_doc

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/914).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#918
- ingadhoc/odoo-argentina#919

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#918
- ingadhoc/odoo-argentina#919

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#918
- ingadhoc/odoo-argentina#919

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#918
- ingadhoc/odoo-argentina#919

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#918
- ingadhoc/odoo-argentina#919

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#918
- ingadhoc/odoo-argentina#919

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#918
- ingadhoc/odoo-argentina#919

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#918
- ingadhoc/odoo-argentina#919

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina#918
- ingadhoc/odoo-argentina#919

**Pull request closed without merging**
