### PR TITLE
[FW][IMP] l10n_ar_account_withholding: when to show help padron

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Si no pudimos obtener la informacion del padron arba mostramos el error avisando que es un error de dicho padron y damos la opcion al cliente de cargarlo manualmente

Forward-Port-Of: ingadhoc/odoo-argentina#665

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/668).

**Comment by fw-bot-adhoc** [comment]
@zaoral @ica-adhoc cherrypicking of pull request ingadhoc/odoo-argentina#665 failed.

stdout:
```
Auto-merging l10n_ar_account_withholding/models/res_company.py
CONFLICT (content): Merge conflict in l10n_ar_account_withholding/models/res_company.py

```

stderr:
```
14:08:31.201436 git.c:444               trace: built-in: git cherry-pick 207a8a7940d43c0c52651c377d393b18471a1d74
error: could not apply 207a8a7... [IMP] l10n_ar_account_withholding: when to show help padron
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by zaoral** [comment]
@fw-bot-adhoc r+

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@zaoral I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
